#
# INCLUDE
################################################################################
imports:
    - { resource: doctrine.yml }
    - { resource: parameters.yml }
################################################################################
