<?php

namespace DTC\Modules\GestionReservationAuto\Repository;

use DTC\Common\Kernel\Extensions\Doctrine\SqlSrv\ORM\CustomEntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimetreRepository extends CustomEntityRepository
{

    public function initServicesFromList(
    \DTC\Modules\GestionReservationAuto\Entity\Perimetre $perimetre)
    {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('so')
                ->from('\DTC\Modules\GestionReservationAuto\Entity\Organization\SourceOrga', 'so', 'so.code');


        $sos = $qb->andWhere($qb->expr()->in('so.code', $perimetre->getListeServices()))
                ->orderBy('so.entLibelle', 'ASC')
                ->getQuery()
                ->getResult();

        $perimetre->setServices(new \Doctrine\Common\Collections\ArrayCollection($sos));
    }

    public function getPerimetresByOneService(
    \DTC\Modules\GestionReservationAuto\Entity\Organization\SourceOrga $so
    )
    {
        $qb = $this->createQueryBuilder('perimetre');
        return $qb->join('perimetre.services', 'so')
                ->where('so.code = :so')
                ->setParameter('so', $so->getCode());
    }

}
