<?php

namespace DTC\Modules\GestionReservationAuto\Repository;

use DTC\Common\Kernel\Extensions\Doctrine\SqlSrv\ORM\CustomEntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistreRepository extends CustomEntityRepository
{
    public function findByService(\DTC\Modules\GestionReservationAuto\Entity\Organization\SourceOrga $so){
        $qb = $this->getEntityManager()
                   ->getRepository('\DTC\Modules\GestionReservationAuto\Entity\Registre')
                   ->createQueryBuilder('r')
                   ->join('r.user','u')
                   ->join('u.sourceAgent', 'sa')
                   ->where('sa.sourceOrgaAffectectation = :so')
                   ->setParameter('so', $so)
                   ->getQuery()
                   ->getResult();
        return $qb;
    }
}

