#
# INCLUDE
################################################################################
imports:
    - { resource: config.yml }
################################################################################


#
# CONFIGURATION
################################################################################